// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4RK1jGqXtyTdl1RU7lqZ_zWU-pIUhJjs',
    appId: '1:478267769285:android:eafe5a380d4372fe900bac',
    messagingSenderId: '478267769285',
    projectId: 'iotecg',
    databaseURL: 'https://iotecg-default-rtdb.firebaseio.com',
    storageBucket: 'iotecg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFkafOAp2Lq4FdjS5Wpi-7CR6W4KmpoOY',
    appId: '1:478267769285:ios:f79f40e6c32db097900bac',
    messagingSenderId: '478267769285',
    projectId: 'iotecg',
    databaseURL: 'https://iotecg-default-rtdb.firebaseio.com',
    storageBucket: 'iotecg.appspot.com',
    iosClientId: '478267769285-fqddtvg7gu90upcp0n6t5ov0iqlt3rbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.bfcai',
  );
}
